server:
  port: 80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
logging:
  level:
    com.jepusi.service.OrderFeignService: debug
ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000