server:
  port: 8001

#数据源的配置
spring:
  application:
    name: cloud-provider-services
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/springcloud2021?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

#mybatis配置
mybatis:
  mapper-locations:
  type-aliases-package:
